spring.cache.type=simple

# Disable datasource/JPA auto-config
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Set server port
server.port=8082

# External API URL for housing price predictions
ml.api.url=http://housing-price-api:8000